package armyc2.c2sd.renderer.test3;

import armyc2.c2sd.JavaLineArray.TacticalLines;
import armyc2.c2sd.renderer.utilities.RendererSettings;
import armyc2.c2sd.renderer.test3.R;

/**
 *
 * @author Michael Deutch
 */
public final class clsSymbolCodeUtility
{
    protected static String GetSymbolCode(int linetype,int rev)
    {
        //String symbolCode="G*TPB-----****X";
        switch(linetype)
        {
            //Basic Shapes
            case TacticalLines.BS_AREA:
                return "BS_AREA--------";
            case TacticalLines.BS_LINE:
                return "BS_LINE--------";
            case TacticalLines.BS_CROSS:
                return "BS_CROSS-------";
            case TacticalLines.BS_ELLIPSE:
                return "BS_ELLIPSE-----";
            case TacticalLines.BS_RECTANGLE:
                return "BS_RECTANGLE---";
                
            //MECTOCs
            case TacticalLines.CORDONKNOCK:
                return "G*TP2-----****X";
            case TacticalLines.CORDONSEARCH:
                return "G*TPV-----****X";
            case TacticalLines.PIPE:
                return "WO-DMPA----L---";
            case TacticalLines.OIL_RIG_FIELD:
                return "WO-DMOA-----A--";
            case TacticalLines.CANAL:
                return "WO-DMCD----L---";
            case TacticalLines.SUBMERGED_CRIB:
                return "WO-DMCC-----A--";
            case TacticalLines.CABLE:
                return "WO-DMCA----L---";
            case TacticalLines.OPERATOR_DEFINED:
                return "WO-DL-O-----A--";
            case TacticalLines.TRAINING_AREA:
                return "WO-DL-TA----A--";
            case TacticalLines.SWEPT_AREA:
                return "WO-DL-SA----A--";
            case TacticalLines.RESTRICTED_AREA:
                return "WO-DL-RA---L---";
            case TacticalLines.MARITIME_AREA:
                return "WO-DL-MA----A--";
            case TacticalLines.MARITIME_LIMIT:
                return "WO-DL-ML---L---";
            case TacticalLines.BOTTOM_TYPE_C3:
                return "WO-DGMBTI---A--";
            case TacticalLines.BOTTOM_TYPE_C2:
                return "WO-DGMBTH---A--";
            case TacticalLines.BOTTOM_TYPE_C1:
                return "WO-DGMBTG---A--";
            case TacticalLines.BOTTOM_TYPE_B3:
                return "WO-DGMBTF---A--";
            case TacticalLines.BOTTOM_TYPE_B2:
                return "WO-DGMBTE---A--";
            case TacticalLines.BOTTOM_TYPE_B1:
                return "WO-DGMBTD---A--";
            case TacticalLines.BOTTOM_TYPE_A3:
                return "WO-DGMBTC---A--";
            case TacticalLines.BOTTOM_TYPE_A2:
                return "WO-DGMBTB---A--";
            case TacticalLines.BOTTOM_TYPE_A1:
                return "WO-DGMBTA---A--";
            case TacticalLines.BOTTOM_CATEGORY_C:
                return "WO-DGMBCC---A--";
            case TacticalLines.BOTTOM_CATEGORY_B:
                return "WO-DGMBCB---A--";
            case TacticalLines.BOTTOM_CATEGORY_A:
                return "WO-DGMBCA---A--";
            case TacticalLines.IMPACT_BURIAL_100:
                return "WO-DGMIBE---A--";
            case TacticalLines.IMPACT_BURIAL_75:
                return "WO-DGMIBD---A--";
            case TacticalLines.IMPACT_BURIAL_20:
                return "WO-DGMIBC---A--";
            case TacticalLines.IMPACT_BURIAL_10:
                return "WO-DGMIBB---A--";
            case TacticalLines.IMPACT_BURIAL_0:
                return "WO-DGMIBA---A--";
            case TacticalLines.CLUTTER_HIGH:
                return "WO-DGMCH----A--";
            case TacticalLines.CLUTTER_MEDIUM:
                return "WO-DGMCM----A--";
            case TacticalLines.CLUTTER_LOW:
                return "WO-DGMCL----A--";
            case TacticalLines.BOTTOM_ROUGHNESS_ROUGH:
                return "WO-DGMRR----A--";
            case TacticalLines.BOTTOM_ROUGHNESS_MODERATE:
                return "WO-DGMRM----A--";
            case TacticalLines.BOTTOM_ROUGHNESS_SMOOTH:
                return "WO-DGMRS----A--";
            case TacticalLines.BOTTOM_SEDIMENTS_NO_DATA:
                return "WO-DGMN-----A--";
            case TacticalLines.BOTTOM_SEDIMENTS_LAND:
                return "WO-DGML-----A--";
            case TacticalLines.SAND_AND_SHELLS:
                return "WO-DGMS-SH--A--";
            case TacticalLines.PEBBLES:
                return "WO-DGMS-PH--A--";
            case TacticalLines.OYSTER_SHELLS:
                return "WO-DGMS-CO--A--";
            case TacticalLines.BOULDERS:
                return "WO-DGMSB----A--";
            case TacticalLines.COARSE_SILT:
                return "WO-DGMSIC---A--";
            case TacticalLines.MEDIUM_SILT:
                return "WO-DGMSIM---A--";
            case TacticalLines.FINE_SILT:
                return "WO-DGMSIF---A--";
            case TacticalLines.VERY_FINE_SILT:
                return "WO-DGMSIVF--A--";
            case TacticalLines.VERY_FINE_SAND:
                return "WO-DGMSSVF--A--";
            case TacticalLines.FINE_SAND:
                return "WO-DGMSSF---A--";
            case TacticalLines.MEDIUM_SAND:
                return "WO-DGMSSM---A--";
            case TacticalLines.COARSE_SAND:
                return "WO-DGMSSC---A--";
            case TacticalLines.VERY_COARSE_SAND:
                return "WO-DGMSSVS--A--";
            case TacticalLines.CLAY:
                return "WO-DGMSC----A--";
            case TacticalLines.SOLID_ROCK:
                return "WO-DGMSR----A--";
            case TacticalLines.BEACH_SLOPE_STEEP:
                return "WO-DBST-----A--";
            case TacticalLines.BEACH_SLOPE_MODERATE:
                return "WO-DBSM-----A--";
            case TacticalLines.BEACH_SLOPE_GENTLE:
                return "WO-DBSG-----A--";
            case TacticalLines.BEACH_SLOPE_FLAT:
                return "WO-DBSF-----A--";
            case TacticalLines.VDR_LEVEL_910:
                return "WO-DOBVI----A--";
            case TacticalLines.VDR_LEVEL_89:
                return "WO-DOBVH----A--";
            case TacticalLines.VDR_LEVEL_78:
                return "WO-DOBVG----A--";
            case TacticalLines.VDR_LEVEL_67:
                return "WO-DOBVF----A--";
            case TacticalLines.VDR_LEVEL_56:
                return "WO-DOBVE----A--";
            case TacticalLines.VDR_LEVEL_45:
                return "WO-DOBVD----A--";
            case TacticalLines.VDR_LEVEL_34:
                return "WO-DOBVC----A--";
            case TacticalLines.VDR_LEVEL_23:
                return "WO-DOBVB----A--";
            case TacticalLines.VDR_LEVEL_12:
                return "WO-DOBVA----A--";
            case TacticalLines.FLOOD_TIDE:
                return "WO-DTCCCFF-L---";
            case TacticalLines.EBB_TIDE:
                return "WO-DTCCCFE-L---";
            case TacticalLines.DISCOLORED_WATER:
                return "WO-DHHDD----A--";
            case TacticalLines.REEF:
                return "WOS-HHDR---L---";
            case TacticalLines.BREAKERS:
                return "WO-DHHDB---L---";
            case TacticalLines.KELP:
                return "WO-DHHDK----A--";
            case TacticalLines.FOUL_GROUND:
                return "WO-DHHDF----A--";
            case TacticalLines.UNDERWATER_HAZARD:
                return "WO-DHHD-----A--";
            case TacticalLines.LEADING_LINE:
                return "WO-DHALLA--L---";
            case TacticalLines.PERCHES:
                return "WO-DHABP----A--";
            case TacticalLines.SEAWALL:
                return "WO-DHPSPS--L---";
            case TacticalLines.JETTY_ABOVE_WATER:
                return "WO-DHPSPA--L---";
            case TacticalLines.JETTY_BELOW_WATER:
                return "WO-DHPSPB--L---";
            case TacticalLines.RAMP_BELOW_WATER:
                return "WO-DHPMRB--L---";
            case TacticalLines.RAMP_ABOVE_WATER:
                return "WO-DHPMRA--L---";
            case TacticalLines.LOADING_FACILITY_AREA:
                return "WO-DHPMO----A--";
            case TacticalLines.LOADING_FACILITY_LINE:
                return "WO-DHPMO---L---";
            case TacticalLines.DRYDOCK:
                return "WO-DHPMD----A--";
            case TacticalLines.PIER:
                return "WO-DHPBP---L---";
            case TacticalLines.ANCHORAGE_AREA:
                return "WO-DHPBA----A--";
            case TacticalLines.ANCHORAGE_LINE:
                return "WO-DHPBA---L---";
            case TacticalLines.FORESHORE_AREA:
                return "WO-DHCF-----A--";
            case TacticalLines.FORESHORE_LINE:
                return "WO-DHCF----L---";
            case TacticalLines.WATER:
                return "WO-DHCW-----A--";
            case TacticalLines.BEACH:
                return "WO-DHCB-----A--";
            case TacticalLines.COASTLINE:
                return "WO-DHCC----L---";
            case TacticalLines.DEPTH_CONTOUR:
                return "WO-DHDDC---L---";
            case TacticalLines.ESTIMATED_ICE_EDGE:
                return "WO-DILIEE--L---";
            case TacticalLines.FREEFORM:
                return "WA-DBAFF----A--";
            case TacticalLines.SAND:
                return "WA-DBAD-----A--";
            case TacticalLines.FOG:
                return "WA-DBAFG----A--";
            case TacticalLines.THUNDERSTORMS:
                return "WA-DBAT-----A--";
            case TacticalLines.FROZEN:
                return "WA-DBAFP----A--";
            case TacticalLines.CONVECTIVE:
                return "WA-DBALPC---A--";
            case TacticalLines.NON_CONVECTIVE:
                return "WA-DBALPNC--A--";
            case TacticalLines.ICING:
                return "WA-DBAI-----A--";
            case TacticalLines.TURBULENCE:
                return "WA-DBATB----A--";
            case TacticalLines.MVFR:
                return "WA-DBAMV----A--";
            case TacticalLines.IFR:
                return "WA-DBAIF----A--";
                
            case TacticalLines.STREAM:
                return "WA-DWS-----L---";
            case TacticalLines.JET:
                return "WA-DWJ-----L---";
            case TacticalLines.ITD:
                return "WA-DPXITD--L---";
            case TacticalLines.ITC:
                return "WA-DPXITCZ-L---";
            case TacticalLines.CONVERGANCE:
                return "WA-DPXCV---L---";
            case TacticalLines.SHEAR:
                return "WA-DPXSH---L---";
            case TacticalLines.INSTABILITY:
                return "WA-DPXIL---L---";
            case TacticalLines.SQUALL:
                return "WA-DPXSQ---L---";
            case TacticalLines.RIDGE:
                return "WA-DPXR----L---";
            case TacticalLines.TROUGH:
                return "WA-DPXT----L---";
            case TacticalLines.SFY:
                return "WA-DPFS-FY-L---";
            case TacticalLines.SFG:
                return "WA-DPFS-FG-L---";
            case TacticalLines.USF:
                return "WA-DPFSU---L---";
            case TacticalLines.SF:
                return "WA-DPFS----L---";
            case TacticalLines.OFY:
                return "WA-DPFO-FY-L---";
            case TacticalLines.UOF:
                return "WA-DPFOU---L---";
            case TacticalLines.OCCLUDED:
                return "WA-DPFO----L---";
            case TacticalLines.WFY:
                return "WA-DPFW-FY-L---";
            case TacticalLines.WFG:
                return "WA-DPFW-FG-L---";
            case TacticalLines.UWF:
                return "WA-DPFWU---L---";
            case TacticalLines.WF:
                return "WA-DPFW----L---";
            case TacticalLines.CFY:
                return "WA-DPFC-FY-L---";
            case TacticalLines.CFG:
                return "WA-DPFC-FG-L---";
            case TacticalLines.UCF:
                return "WA-DPFCU---L---";
            case TacticalLines.CF:
                return "WA-DPFC----L---";
            case TacticalLines.ISLAND:
                return "WO-DHCI-----A--";
            case TacticalLines.DEPTH_AREA:
                return "WO-DHDDA----A--";
            case TacticalLines.DEPTH_CURVE:
                return "WO-DHDDL---L---";
            case TacticalLines.ICE_OPENINGS_FROZEN:
                return "WO-DIOLF---L---";
            case TacticalLines.ICE_OPENINGS_LEAD:
                return "WO-DIOL----L---";
            case TacticalLines.CRACKS_SPECIFIC_LOCATION:
                return "WO-DIOCS---L---";
            case TacticalLines.CRACKS:
                return "WO-DIOC----L---";
            case TacticalLines.ICE_EDGE_RADAR:
                return "WO-DILIER--L---";
            case TacticalLines.ICE_EDGE:
                return "WO-DILIEO--L---";
            case TacticalLines.LRO:
                return "WO-DILOR---L---";
            case TacticalLines.UNDERCAST:
                return "WO-DILUC---L---";
            case TacticalLines.LVO:
                return "WO-DILOV---L---";
            case TacticalLines.OPERATOR_FREEFORM:
                return "WA-DIPFF---L---";
            case TacticalLines.ISODROSOTHERM:
                return "WA-DIPID---L---";
            case TacticalLines.ISOBAR:
                return "WA-DIPIB---L---";
            case TacticalLines.ISOPLETHS:
                return "WA-DIPTH---L---";
            case TacticalLines.UPPER_AIR:
                return "WA-DIPCO---L---";
            case TacticalLines.ISOTHERM:
                return "WA-DIPIS---L---";
            case TacticalLines.ISOTACH:
                return "WA-DIPIT---L---";
            case TacticalLines.WEIRS:
                return "WOS-HPFF----A--";

            case TacticalLines.OVERHEAD_WIRE:
                return "G*MPOHO---****X";
            case TacticalLines.BLOCK:
                return "G*TPB-----****X";
            case TacticalLines.BREACH:
                return"G*TPH-----****X";
            case TacticalLines.BYPASS:
                return "G*TPY-----****X";
            case TacticalLines.CANALIZE:
                return "G*TPC-----****X";
            case TacticalLines.CLEAR:
                return "G*TPX-----****X";
            case TacticalLines.CONTAIN:
                return "G*TPJ-----****X";
            case TacticalLines.CATK:
                return "G*TPK-----****X";
            case TacticalLines.CATKBYFIRE:
                return "G*TPKF----****X";
            case TacticalLines.DELAY:
                return "G*TPL-----****X";
            case TacticalLines.DISRUPT:
                return "G*TPT-----****X";
            case TacticalLines.FIX:
                return "G*TPF-----****X";
            case TacticalLines.FOLLA:
                return "G*TPA-----****X";
            case TacticalLines.FOLSP:
                return "G*TPAS----****X";
            case TacticalLines.ISOLATE:
                return "G*TPE-----****X";
            case TacticalLines.OCCUPY:
                return "G*TPO-----****X";
            case TacticalLines.PENETRATE:
                return "G*TPP-----****X";
            case TacticalLines.RIP:
                return "G*TPR-----****X";
            case TacticalLines.RETAIN:
                return "G*TPQ-----****X";
            case TacticalLines.RETIRE:
                return "G*TPM-----****X";
            case TacticalLines.SECURE:
                return "G*TPS-----****X";
            case TacticalLines.SCREEN:
            case TacticalLines.SCREEN_REVC:
                return "G*TPUS----****X";
            case TacticalLines.COVER:
            case TacticalLines.COVER_REVC:
                return "G*TPUC----****X";
            case TacticalLines.GUARD:
            case TacticalLines.GUARD_REVC:
                return "G*TPUG----****X";
            case TacticalLines.SEIZE:
            case TacticalLines.SEIZE_REVC:
                return "G*TPZ-----****X";
            case TacticalLines.WITHDRAW:
                return "G*TPW-----****X";
            case TacticalLines.WDRAWUP:
                return "G*TPWP----****X";
            case TacticalLines.BOUNDARY:
                return "G*GPGLB---****X";
            case TacticalLines.FLOT:
                return "G*GPGLF---****X";
            case TacticalLines.LC:
                return "G*GPGLC---****X";
            case TacticalLines.PL:
                return "G*GPGLP---****X";
            case TacticalLines.LL:
                return "G*GPGLL---****X";
            case TacticalLines.GENERAL:
                return "G*GPGAG---****X";
            case TacticalLines.GENERIC:
                return "GENERIC---****X";
            case TacticalLines.ASSY:
                return "G*GPGAA---****X";
            case TacticalLines.EA:
                return "G*GPGAE---****X";
            case TacticalLines.FORT:
                return "G*GPGAF---****X";
            case TacticalLines.DZ:
                return "G*GPGAD---****X";
            case TacticalLines.EZ:
                return "G*GPGAX---****X";
            case TacticalLines.LZ:
                return "G*GPGAL---****X";
            case TacticalLines.PZ:
                return "G*GPGAP---****X";
            case TacticalLines.SARA:
                return "G*GPGAS---****X";
            case TacticalLines.LAA:
                return "G*GPGAY---****X";
            case TacticalLines.AIRFIELD:
                return "G*GPGAZ---****X";
            case TacticalLines.AC:
                return "G*GPALC---****X";
            case TacticalLines.MRR:
            case TacticalLines.MRR_USAS:
                return "G*GPALM---****X";
            case TacticalLines.SAAFR:
                return "G*GPALS---****X";
            case TacticalLines.UAV:
            case TacticalLines.UAV_USAS:
                return "G*GPALU---****X";
            case TacticalLines.LLTR:
                return "G*GPALL---****X";
            case TacticalLines.ROZ:
                return "G*GPAAR---****X";
            case TacticalLines.FAADZ:
                return "G*GPAAF---****X";
            case TacticalLines.HIDACZ:
                return "G*GPAAH---****X";
            case TacticalLines.MEZ:
                return "G*GPAAM---****X";
            case TacticalLines.LOMEZ:
                return "G*GPAAML--****X";
            case TacticalLines.HIMEZ:
                return "G*GPAAMH--****X";
            case TacticalLines.WFZ:
                return "G*GPAAW---****X";
            case TacticalLines.DECEIVE:
                return "G*GPPD----****X";
            case TacticalLines.AAFNT:
                return "G*GPPA----****X";
            case TacticalLines.DIRATKFNT:
                return "G*GPPF----****X";
            case TacticalLines.DMA:
                return "G*GPPM----****X";
            case TacticalLines.DMAF:
                return "G*GPPY----****X";
            case TacticalLines.DUMMY:
                return "G*GPPC----****X";
            case TacticalLines.FEBA:
                return "G*GPDLF---****X";
            case TacticalLines.PDF:
                return "G*GPDLP---****X";
            case TacticalLines.BATTLE:
                return "G*GPDAB---****X";
            case TacticalLines.PNO:
                return "G*GPDABP--****X";
            case TacticalLines.EA1:
                return "G*GPDAE---****X";
            case TacticalLines.AXAD:
                return "G*GPOLAV--****X";
            case TacticalLines.AIRAOA:
                return "G*GPOLAA--****X";
            case TacticalLines.AAAAA:
                return "G*GPOLAR--****X";
            case TacticalLines.MAIN:
                return "G*GPOLAGM-****X";
            case TacticalLines.SPT:
                return "G*GPOLAGS-****X";
            case TacticalLines.DIRATKAIR:
                return "G*GPOLKA--****X";
            case TacticalLines.DIRATKGND:
                return "G*GPOLKGM-****X";
            case TacticalLines.DIRATKSPT:
                return "G*GPOLKGS-****X";
            case TacticalLines.FCL:
                return "G*GPOLF---****X";
            case TacticalLines.IL:
                return "G*GPOLI---****X";
            case TacticalLines.LOA:
                return "G*GPOLL---****X";
            case TacticalLines.LOD:
                return "G*GPOLT---****X";
            case TacticalLines.LDLC:
                return "G*GPOLC---****X";
            case TacticalLines.PLD:
                return "G*GPOLP---****X";
            case TacticalLines.ASSAULT:
                return "G*GPOAA---****X";
            case TacticalLines.ATKPOS:
                return "G*GPOAK---****X";
            case TacticalLines.ATKBYFIRE:
                return "G*GPOAF---****X";
            case TacticalLines.SPTBYFIRE:
                return "G*GPOAS---****X";
            case TacticalLines.OBJ:
                return "G*GPOAO---****X";
            case TacticalLines.PEN:
                return "G*GPOAP---****X";
            case TacticalLines.AMBUSH:
                return "G*GPSLA---****X";
            case TacticalLines.HOLD:
                return "G*GPSLH---****X";
            case TacticalLines.RELEASE:
                return "G*GPSLR---****X";
            case TacticalLines.BRDGHD:
                return "G*GPSLB---****X";
            case TacticalLines.AO:
                return "G*GPSAO---****X";
            case TacticalLines.AIRHEAD:
                return "G*GPSAA---****X";
            case TacticalLines.ENCIRCLE:
                return "G*GPSAE---****X";
            case TacticalLines.NAI:
                return "G*GPSAN---****X";
            case TacticalLines.TAI:
                return "G*GPSAT---****X";
            case TacticalLines.BELT:
            case TacticalLines.BELT1:
                return "G*MPOGB---****X";
            case TacticalLines.LINE:
                return "G*MPOGL---****X";
            case TacticalLines.ZONE:
                return "G*MPOGZ---****X";
            case TacticalLines.OBSFAREA:
                return "G*MPOGF---****X";
            case TacticalLines.OBSAREA:
                return "G*MPOGR---****X";
            case TacticalLines.ABATIS:
                return "G*MPOS----****X";
            case TacticalLines.ATDITCH:
                return "G*MPOADU--****X";
            case TacticalLines.ATDITCHC:
                return "G*MPOADC--****X";
            case TacticalLines.ATDITCHM:
                return "G*MPOAR---****X";
            case TacticalLines.ATWALL:
                return "G*MPOAW---****X";
            case TacticalLines.CLUSTER:
                return "G*MPOMC---****X";
            case TacticalLines.DEPICT:
                return "G*MPOFD---****X";
            case TacticalLines.GAP:
                return "G*MPOFG---****X";
            case TacticalLines.MINED:
                return "G*MPOFA---****X";
            case TacticalLines.MNFLDBLK:
                return "G*MPOEB---****X";
            case TacticalLines.MNFLDFIX:
                return "G*MPOEF---****X";
            case TacticalLines.TURN:
                return "G*MPOET---****X";
            case TacticalLines.MNFLDDIS:
                return "G*MPOED---****X";
            case TacticalLines.UXO:
                return "G*MPOU----****X";
            case TacticalLines.PLANNED:
                return "G*MPORP---****X";
            case TacticalLines.ESR1:
                return "G*MPORS---****X";
            case TacticalLines.ESR2:
                return "G*MPORA---****X";
            case TacticalLines.ROADBLK:
                return "G*MPORC---****X";
            case TacticalLines.TRIP:
                return "G*MPOT----****X";
            case TacticalLines.UNSP:
                return "G*MPOWU---****X";
            case TacticalLines.SFENCE:
                return "G*MPOWS---****X";
            case TacticalLines.DFENCE:
                return "G*MPOWD---****X";
            case TacticalLines.DOUBLEA:
                return "G*MPOWA---****X";
            case TacticalLines.LWFENCE:
                return "G*MPOWL---****X";
            case TacticalLines.HWFENCE:
                return "G*MPOWH---****X";
            case TacticalLines.SINGLEC:
                return "G*MPOWCS--****X";
            case TacticalLines.DOUBLEC:
                return "G*MPOWCD--****X";
            case TacticalLines.TRIPLE:
                return "G*MPOWCT--****X";
            case TacticalLines.EASY:
                return "G*MPBDE---****X";
            case TacticalLines.BYDIF:
                return "G*MPBDD---****X";
            case TacticalLines.BYIMP:
                return "G*MPBDI---****X";
            case TacticalLines.ASLTXING:
                return "G*MPBCA---****X";
            case TacticalLines.BRIDGE:
                return "G*MPBCB---****X";
            case TacticalLines.FERRY:
                return "G*MPBCF---****X";
            case TacticalLines.FORDSITE:
                return "G*MPBCE---****X";
            case TacticalLines.FORDIF:
                return "G*MPBCD---****X";
            case TacticalLines.MFLANE:
                return "G*MPBCL---****X";
            case TacticalLines.RAFT:
                return "G*MPBCR---****X";
            case TacticalLines.FORTL:
                return "G*MPSL----****X";
            case TacticalLines.FOXHOLE:
                return "G*MPSW----****X";
            case TacticalLines.STRONG:
                return "G*MPSP----****X";
            case TacticalLines.MSDZ:
                return "G*MPNM----****X";
            case TacticalLines.RAD:
                return "G*MPNR----****X";
            case TacticalLines.CHEM:
                return "G*MPNC----****X";
            case TacticalLines.BIO:
                return "G*MPNB----****X";
            case TacticalLines.DRCL:
                return "G*MPNL----****X";
            case TacticalLines.LINTGT:
                return "G*FPLT----****X";
            case TacticalLines.LINTGTS:
                return "G*FPLTS---****X";
            case TacticalLines.FPF:
                return "G*FPLTF---****X";
            case TacticalLines.FSCL:
                return "G*FPLCF---****X";
            case TacticalLines.CFL:
                return "G*FPLCC---****X";
            case TacticalLines.NFL:
                return "G*FPLCN---****X";
            case TacticalLines.MFP:
                return "G*FPLCM---****X";
            case TacticalLines.TGMF:
                return "G*FPACT---****X";
            case TacticalLines.RFL:
                return "G*FPLCR---****X";
            case TacticalLines.AT:
                return "G*FPAT----****X";
            case TacticalLines.RECTANGULAR:
                return "G*FPATR---****X";
            case TacticalLines.CIRCULAR:
                return "G*FPATC---****X";
            case TacticalLines.SERIES:
                return "G*FPATG---****X";
            case TacticalLines.SMOKE:
                return "G*FPATS---****X";
            case TacticalLines.BOMB:
                return "G*FPATB---****X";
            case TacticalLines.FSA:
                return "G*FPACSI--****X";
            case TacticalLines.FSA_RECTANGULAR:
                return "G*FPACSR--****X";
            case TacticalLines.FSA_CIRCULAR:
                return "G*FPACSC--****X";
            case TacticalLines.ACA:
                return "G*FPACAI--****X";
            case TacticalLines.ACA_RECTANGULAR:
                return "G*FPACAR--****X";
            case TacticalLines.ACA_CIRCULAR:
                return "G*FPACAC--****X";

            case TacticalLines.FFA:
                return "G*FPACFI--****X";
            case TacticalLines.FFA_RECTANGULAR:
                return "G*FPACFR--****X";
            case TacticalLines.FFA_CIRCULAR:
                return "G*FPACFC--****X";

            case TacticalLines.NFA:
                return "G*FPACNI--****X";
            case TacticalLines.NFA_RECTANGULAR:
                return "G*FPACNR--****X";
            case TacticalLines.NFA_CIRCULAR:
                return "G*FPACNC--****X";

            case TacticalLines.RFA:
                return "G*FPACRI--****X";
            case TacticalLines.RFA_RECTANGULAR:
                return "G*FPACRR--****X";
            case TacticalLines.RFA_CIRCULAR:
                return "G*FPACRC--****X";

            case TacticalLines.PAA_RECTANGULAR:
            case TacticalLines.PAA_RECTANGULAR_REVC:
            case TacticalLines.PAA:
                return "G*FPACPR--****X";
            case TacticalLines.PAA_CIRCULAR:
                return "G*FPACPC--****X";

            case TacticalLines.ATI:
                return "G*FPAZII--****X";
            case TacticalLines.ATI_RECTANGULAR:
                return "G*FPAZIR--****X";
            case TacticalLines.ATI_CIRCULAR:
                return "G*FPAZIC--****X";

            case TacticalLines.CFFZ:
                return "G*FPAZXI--****X";
            case TacticalLines.CFFZ_RECTANGULAR:
                return "G*FPAZXR--****X";
            case TacticalLines.CFFZ_CIRCULAR:
                return "G*FPAZXC--****X";

            case TacticalLines.SENSOR:
                if(rev==RendererSettings.Symbology_2525C)
                    return "G*FPACEI--****X";
                return "G*FPAZSI--****X";
            case TacticalLines.SENSOR_RECTANGULAR:
                if(rev==RendererSettings.Symbology_2525C)
                    return "G*FPACER--****X";
                return "G*FPAZSR--****X";
            case TacticalLines.SENSOR_CIRCULAR:
                if(rev==RendererSettings.Symbology_2525C)
                    return "G*FPACEC--****X";
                return "G*FPAZSC--****X";

            case TacticalLines.CENSOR:
                return "G*FPAZCI--****X";
            case TacticalLines.CENSOR_RECTANGULAR:
                return "G*FPAZCR--****X";
            case TacticalLines.CENSOR_CIRCULAR:
                return "G*FPAZCC--****X";

            case TacticalLines.DA:
                if(rev==RendererSettings.Symbology_2525C)
                    return "G*FPACDI--****X";
                return "G*FPAZDI--****X";
            case TacticalLines.DA_RECTANGULAR:
                if(rev==RendererSettings.Symbology_2525C)
                    return "G*FPACDR--****X";
                return "G*FPAZDR--****X";
            case TacticalLines.DA_CIRCULAR:
                if(rev==RendererSettings.Symbology_2525C)
                    return "G*FPACDC--****X";
                return "G*FPAZDC--****X";

            case TacticalLines.CFZ:
                return "G*FPAZFI--****X";
            case TacticalLines.CFZ_RECTANGULAR:
                return "G*FPAZFR--****X";
            case TacticalLines.CFZ_CIRCULAR:
                return "G*FPAZFC--****X";

            case TacticalLines.ZOR:
                if(rev==RendererSettings.Symbology_2525C)
                    return "G*FPACZI--****X";
                return "G*FPAZZI--****X";
            case TacticalLines.ZOR_RECTANGULAR:
                if(rev==RendererSettings.Symbology_2525C)
                    return "G*FPACZR--****X";
                return "G*FPAZZR--****X";
            case TacticalLines.ZOR_CIRCULAR:
                if(rev==RendererSettings.Symbology_2525C)
                    return "G*FPACZC--****X";
                return "G*FPAZZC--****X";

            case TacticalLines.TBA:
                if(rev==RendererSettings.Symbology_2525C)
                    return "G*FPACBI--****X";
                return "G*FPAZBI--****X";
            case TacticalLines.TBA_RECTANGULAR:
                if(rev==RendererSettings.Symbology_2525C)
                    return "G*FPACBR--****X";
                return "G*FPAZBR--****X";
            case TacticalLines.TBA_CIRCULAR:
                if(rev==RendererSettings.Symbology_2525C)
                    return "G*FPACBC--****X";
                return "G*FPAZBC--****X";

            case TacticalLines.TVAR:
                if(rev==RendererSettings.Symbology_2525C)
                    return "G*FPACVI--****X";
                return "G*FPAZVI--****X";
            case TacticalLines.TVAR_RECTANGULAR:
                if(rev==RendererSettings.Symbology_2525C)
                    return "G*FPACVR--****X";
                return "G*FPAZVR--****X";
            case TacticalLines.TVAR_CIRCULAR:
                if(rev==RendererSettings.Symbology_2525C)
                    return "G*FPACVC--****X";
                return "G*FPAZVC--****X";

            case TacticalLines.KILLBOXBLUE:
                return "G*FPAKBI--****X";
            case TacticalLines.KILLBOXBLUE_RECTANGULAR:
                return "G*FPAKBR--****X";
            case TacticalLines.KILLBOXBLUE_CIRCULAR:
                return "G*FPAKBC--****X";
                
            case TacticalLines.KILLBOXPURPLE:
                return "G*FPAKPI--****X";
            case TacticalLines.KILLBOXPURPLE_RECTANGULAR:
                return "G*FPAKPR--****X";
            case TacticalLines.KILLBOXPURPLE_CIRCULAR:
                return "G*FPAKPC--****X";
                
            case TacticalLines.RANGE_FAN:
                return "G*FPAXC---****X";
            case TacticalLines.RANGE_FAN_SECTOR:
                return "G*FPAXS---****X";

            case TacticalLines.CONVOY:
                return "G*SPLCM---****X";
            case TacticalLines.HCONVOY:
                return "G*SPLCH---****X";
            case TacticalLines.MSR:
                return "G*SPLRM---****X";
            case TacticalLines.ASR:
                return "G*SPLRA---****X";
            case TacticalLines.ONEWAY:
                return "G*SPLRO---****X";
            case TacticalLines.ALT:
                return "G*SPLRT---****X";
            case TacticalLines.TWOWAY:
                return "G*SPLRW---****X";

            case TacticalLines.DHA:
                return "G*SPAD----****X";
            case TacticalLines.EPW:
                return "G*SPAE----****X";
            case TacticalLines.FARP:
                return "G*SPAR----****X";
            case TacticalLines.RHA:
                return "G*SPAH----****X";
            case TacticalLines.BSA:
                return "G*SPASB---****X";
            case TacticalLines.DSA:
                return "G*SPASD---****X";
            case TacticalLines.RSA:
                return "G*SPASR---****X";

            case TacticalLines.NAVIGATION:
                return "G*OPHN----****X";
            case TacticalLines.BEARING:
                return "G*OPB-----****X";
            case TacticalLines.ELECTRO:
                return "G*OPBE----****X";
            case TacticalLines.ACOUSTIC:
                return "G*OPBA----****X";
            case TacticalLines.TORPEDO:
                return "G*OPBT----****X";
            case TacticalLines.OPTICAL:
                return "G*OPBO----****X";

            default:
                return null;
        }
    }
}
